[package]
name = "rust_gitignore_io"
version = "0.1.0"
authors = ["JEphron"]

[dependencies]
futures = "0.1"
hyper = "0.11"
tokio-core = "0.1"
clap = "2.26.0"
serde = "1.0.12"
serde_derive = "1.0.12"
serde_json = "1.0.3"

